apiVersion: v1
kind: Service
metadata:
  name: {{ include "vandalizer.fullname" . }}-api
  labels:
    {{- include "vandalizer.labels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
  selector:
    {{- include "vandalizer.selectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
