apiVersion: v1
kind: Service
metadata:
  name: {{ include "vandalizer.fullname" . }}-frontend
  labels:
    {{- include "vandalizer.labels" (dict "ctx" . "component" "frontend") | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "vandalizer.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 4 }}
