{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vandalizer.fullname" . }}-mongodb
  labels:
    {{- include "vandalizer.labels" (dict "ctx" . "component" "mongodb") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
      protocol: TCP
  selector:
    {{- include "vandalizer.selectorLabels" (dict "ctx" . "component" "mongodb") | nindent 4 }}
{{- end }}
