{{- if and .Values.redis.enabled .Values.redis.persistence.enabled (not .Values.redis.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vandalizer.fullname" . }}-redis
  labels:
    {{- include "vandalizer.labels" (dict "ctx" . "component" "redis") | nindent 4 }}
  {{- with .Values.redis.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.redis.persistence.accessModes | nindent 4 }}
  {{- include "vandalizer.storageClass" .Values.redis.persistence | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
