import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { createReview } from './harness.mjs'
import { stamp } from './fixtures.mjs'
const review=await createReview({output:process.env.REVIEW_OUTPUT,baseURL:process.env.REVIEW_BASE_URL}),{page}=review
let failures=new Set(),added=0
const app={uuid:'demo-1',name:'Alex Research Administrator',title:'Proposal services lead',email:'alex@example.test',organization:'Institutional Research Administration',status:'active',waitlist_position:null,activated_at:stamp,expires_at:null,tokens_used:400000,tokens_budget:2000000,post_questionnaire_completed:true,admin_released:false,created_at:stamp,questionnaire_responses:{role:'Research administrator'},credentials_sent_at:stamp,last_login_at:stamp,user_is_demo:true}
const fixed={'/api/auth/me':{id:'reviewer',user_id:'reviewer',email:'reviewer@example.test',name:'Alex Morgan',is_admin:true,is_staff:true,current_team:'team-1'},'/api/auth/config':{auth_methods:['password'],oauth_providers:[],trial_system_enabled:true},'/api/admin/system/version':{current:'5.0.0',update_available:false},'/api/admin/catalog/status':{update_available:false},'/api/admin/telemetry/optin':{show_banner:false},'/api/demo/admin/stats':{total_applications:1,active_count:1,waitlist_count:0,expired_count:0,completed_count:0,by_organization:[{organization:app.organization,count:1}]},'/api/support/tickets':{tickets:[],total:0},'/api/feedback/prompts/admin/overview':[{slug:'early',stage:'early',subject:'How is the first document review going?',question_text:'What would make source review easier?',enabled:true,priority:1,trigger_rules:{},stats:{shown:10,responded:5,dismissed:2,response_rate:0.5}}],'/api/demo/admin/responses':[{uuid:'response-1',name:app.name,email:app.email,organization:app.organization,title:app.title,questionnaire_responses:{role:'Research administrator'},responses:{satisfaction:'Somewhat Satisfied',constructive_criticism:'Keep source evidence next to each output.'},created_at:stamp}]}
await page.route('**/api/**',async r=>{const u=new URL(r.request().url()),p=u.pathname.replace(/\/$/,''),m=r.request().method();if(failures.has(m+' '+p))return r.fulfill({status:503,json:{detail:'Demo administration temporarily unavailable'}});if(p==='/api/demo/admin/applications')return r.fulfill({json:!u.searchParams.get('status')||u.searchParams.get('status')==='active'?[app]:[]});if(p==='/api/demo/admin/add-user'){added++;return r.fulfill({json:{ok:true,uuid:'added-1'}})}if(p.includes('/resend-credentials/'))return r.fulfill({json:{ok:false,status:'send_failed',message:'The sign-in email was not sent.'}});if(p in fixed)return r.fulfill({json:fixed[p]});return r.fallback()})
async function shot(id){await review.capture(id);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),id+': overflow');assert.deepEqual(JSON.parse(await readFile(resolve(review.out,id+'.axe.json'),'utf8')),[],id+': accessibility');console.log('Captured '+id)}
try{
 for(const width of [320,1440]){
  await page.setViewportSize({width,height:width===320?700:1000});failures=new Set(['GET /api/demo/admin/applications']);await page.goto(review.baseURL+'/admin?tab=demo');await page.getByRole('button',{name:'Retry demo applications'}).waitFor();failures.clear();await page.getByRole('button',{name:'Retry demo applications'}).click();const table=page.getByRole('region',{name:'Demo applications',exact:true});await table.waitFor();await shot('admin-demo-populated-'+width);const row=table.getByRole('button',{name:app.name,exact:true});await row.focus();await page.keyboard.press('Enter');await page.getByText('Onboarding Responses',{exact:true}).waitFor();await shot('admin-demo-keyboard-details-'+width)
  await page.getByRole('button',{name:'Add User',exact:true}).click();await page.getByLabel('First Name',{exact:true}).fill('Jordan');await page.getByLabel('Last Name',{exact:true}).fill('Research');await page.getByLabel('Email',{exact:true}).fill('jordan@example.test');failures.add('POST /api/demo/admin/add-user');await page.getByRole('button',{name:'Add & Activate',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByLabel('First Name',{exact:true}).inputValue(),'Jordan');await shot('admin-demo-add-error-'+width);failures.clear();await page.getByRole('button',{name:'Add & Activate',exact:true}).click();await page.getByLabel('First Name',{exact:true}).waitFor({state:'hidden'})
  await table.getByRole('button',{name:'Resend Creds',exact:true}).click();const confirm=page.getByRole('dialog',{name:'Resend credentials?',exact:true});await confirm.getByRole('button',{name:'Resend',exact:true}).click();await page.getByText('The sign-in email was not sent.',{exact:true}).waitFor();await shot('admin-demo-resend-failed-'+width);await page.getByRole('button',{name:'Dismiss error',exact:true}).click()
  failures.add('GET /api/demo/admin/responses');await page.getByRole('button',{name:'Survey Responses',exact:true}).click();await page.getByRole('button',{name:'Retry survey responses'}).waitFor();failures.clear();await page.getByRole('button',{name:'Retry survey responses'}).click();const responses=page.getByRole('region',{name:'Trial survey responses',exact:true});await responses.getByRole('button',{name:app.name,exact:true}).click();await page.getByText('Keep source evidence next to each output.',{exact:true}).waitFor();await shot('admin-demo-survey-details-'+width)
 }
 assert.deepEqual(review.errors,[]);assert.deepEqual([...review.unmatched],[]);review.observations.push('Synthetic conditional Demo admin: list failure/retry, native keyboard row expansion, retained failed add, API-reported resend failure and survey response recovery. No accounts created or emails sent.')
}catch(error){await review.capture('admin-demo-blocked',String(error));throw error}finally{await review.flush();await review.browser.close()}
