import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { createReview } from './harness.mjs'
import { docs } from './fixtures.mjs'
const root=process.env.REVIEW_DOCUMENT_FIXTURES||'/private/tmp/vandalizer-ra8-documents'
const pdf=await readFile('backend/certification-data/documents/budget-justification.pdf'),scan=await readFile(resolve(root,'scanned-budget.pdf')),word=await readFile(resolve(root,'sponsor-review.docx')),sheet=await readFile(resolve(root,'budget.xlsx'))
const text=JSON.parse(await readFile(resolve(root,'pdf-text.json'),'utf8')).text,wordText=JSON.parse(await readFile(resolve(root,'word-text.json'),'utf8')).text,sheets=JSON.parse(await readFile(resolve(root,'sheet-data.json'),'utf8'))
const cases=[['pdf','Multipage budget justification.pdf','application/pdf',pdf,text],['scan','Scanned budget justification.pdf','application/pdf',scan,''],['word','Sponsor review.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',word,wordText],['sheet','Sponsor budget.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',sheet,'']]
const review=await createReview({output:process.env.REVIEW_OUTPUT,baseURL:process.env.REVIEW_BASE_URL}),{page,state}=review
page.setDefaultTimeout(30000)
let failSheet=false
await page.route('**/api/documents/list*',r=>r.fulfill({json:{folders:[],documents:cases.map(([id,title])=>({...docs[0],id,uuid:id,title,extension:title.split('.').at(-1),num_pages:2}))}}))
await page.route('**/api/files/download?*',r=>{const id=new URL(r.request().url()).searchParams.get('docid'),doc=cases.find(c=>c[0]===id);return doc?r.fulfill({contentType:doc[2],headers:{'Content-Length':String(doc[3].length)},body:r.request().method()==='HEAD'?undefined:doc[3]}):r.fallback()})
await page.route('**/api/documents/poll_status?*',r=>{const url=new URL(r.request().url()),id=url.searchParams.get('docid')||url.searchParams.get('doc_uuid')||url.searchParams.get('uuid'),doc=cases.find(c=>c[0]===id);return r.fulfill({json:{status:'SUCCESS',complete:true,valid:true,processing:false,raw_text:doc?.[4]||'',title:doc?.[1]}})})
await page.route('**/api/files/sheet/sheet-json',r=>failSheet?r.fulfill({status:503,json:{detail:'Spreadsheet preview is temporarily unavailable.'}}):r.fulfill({json:sheets}))
async function shot(id){await review.capture(id);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),id+': page overflow');assert.deepEqual(JSON.parse(await readFile(resolve(review.out,id+'.axe.json'),'utf8')),[],id+': accessibility');console.log('Captured '+id)}
async function open(id){await page.goto(review.baseURL+'/?mode=files');await page.getByRole('row',{name:'Document: '+cases.find(c=>c[0]===id)[1],exact:true}).click()}
async function search(query){const find=page.getByRole('button',{name:'Find in document',exact:true});await find.click();const input=page.getByRole('textbox',{name:'Find in document',exact:true});await input.fill(query);const box=await page.getByRole('search').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=page.viewportSize().width);return find}
try{
 for(const width of [320,1440]){
  await page.setViewportSize({width,height:width===320?700:1000});await open('pdf');await page.locator('canvas').nth(1).waitFor();await shot('format-pdf-pages-'+width);const find=await search('Senior Personnel');await page.locator('.pdf-highlight').first().waitFor();await shot('format-pdf-search-'+width);await page.getByRole('button',{name:'Close find'}).click();assert.ok(await find.evaluate(e=>e===document.activeElement));await page.getByRole('button',{name:'View extracted text'}).click();const raw=page.getByRole('dialog',{name:'Extracted Text'});await raw.getByText(/Total Senior Personnel/).waitFor();await shot('format-pdf-extracted-text-'+width);await page.keyboard.press('Escape');await raw.waitFor({state:'hidden'})
  await open('scan');await page.locator('canvas').nth(1).waitFor();await search('Senior Personnel');await page.getByText('No results',{exact:true}).waitFor();assert.equal(await page.locator('.pdf-highlight').count(),0);await shot('format-scan-no-text-match-'+width);await page.getByRole('button',{name:'Close find'}).click();await page.getByRole('button',{name:'View extracted text'}).click();await raw.waitFor();await shot('format-scan-extraction-unavailable-'+width);await page.keyboard.press('Escape')
  await open('word');await page.getByRole('region',{name:'Extracted document text'}).getByText('Equipment',{exact:true}).waitFor();await page.getByRole('button',{name:'Zoom in',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Reset zoom',exact:true}).innerText(),'125%');await search('Equipment');await page.locator('mark.doc-search-hl').first().waitFor();await shot('format-word-table-search-'+width);await page.getByRole('button',{name:'Close find'}).click();await page.getByRole('button',{name:'Reset zoom',exact:true}).click()
  failSheet=true;await open('sheet');await page.getByRole('button',{name:'Retry spreadsheet'}).waitFor();await shot('format-spreadsheet-read-error-'+width);failSheet=false;await page.getByRole('button',{name:'Retry spreadsheet'}).click();await page.getByRole('cell',{name:'128333',exact:true}).waitFor();await page.getByRole('button',{name:'Zoom in',exact:true}).click();await search('Equipment');await page.getByText('1 of 1',{exact:true}).waitFor();await shot('format-spreadsheet-values-search-'+width);await page.getByRole('button',{name:'Close find'}).click();await page.getByRole('button',{name:'Assumptions',exact:true}).click();await page.getByRole('cell',{name:'October 15, 2026 at 5 PM Pacific',exact:true}).waitFor();await shot('format-spreadsheet-second-sheet-'+width)
  await page.goto(review.baseURL+'/?mode=chat');state.chatChunks=[{kind:'sources',content:'',sources:[{document_title:cases[0][1],document_uuid:'pdf',chunk_id:'budget-source',page:1,content_preview:'Total Senior Personnel: $43,333'}]},{kind:'text',content:'The recorded senior-personnel total is $43,333.'}];await page.getByRole('textbox',{name:'Message input'}).fill('Show the personnel total and its source.');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByRole('button',{name:/Multipage budget justification.pdf · p. 1/}).click();await page.getByRole('menuitem',{name:'Open at p. 1',exact:true}).click();await page.locator('.pdf-highlight').first().waitFor();await shot('format-pdf-source-highlight-'+width)
 }
 assert.deepEqual(review.errors,[]);assert.deepEqual([...review.unmatched],[]);review.observations.push('Actual two-page PDF bytes and raster-only variant rendered by PDF.js; DOCX and XLSX generated locally and parsed by application reader functions, including formula total 128333. Intercepted API transport, no live ingestion/OCR/model. PDF search/source highlights, explicit missing scan text, extracted text, Word tables/zoom/search, spreadsheet failure retry, values/search/second sheet at 320/1440.')
}catch(error){await review.capture('document-formats-blocked',String(error));throw error}finally{await review.flush();await review.browser.close()}
