import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { createReview } from './harness.mjs'
const review=await createReview({output:process.env.REVIEW_OUTPUT,baseURL:process.env.REVIEW_BASE_URL}),{page,state}=review
const quality={tier:'good',score:80,accuracy:.8,consistency:1,num_test_cases:2,num_runs:1,last_validated_at:null,plan_stale:true,optimization:{status:'completed',run_uuid:'opt-1',optimized_score:85,baseline_score:70,pending_recommendation:true},active_alerts:[{type:'stale',severity:'warning',message:'Add representative sponsor exceptions before relying on this score. '.repeat(3)}]}
async function shot(id){await review.capture(id);assert.deepEqual(JSON.parse(await readFile(resolve(review.out,id+'.axe.json'),'utf8')),[],id+': accessibility');console.log('Captured '+id)}
try{
 for(const width of [320,768,1440]){
  await page.setViewportSize({width,height:width===320?568:800});await page.goto(review.baseURL+'/?mode=chat');state.chatChunks=[{kind:'tool_call',tool_name:'create_workflow',tool_call_id:'tool-1',args:{name:'Sponsor review'},content:''},{kind:'tool_result',tool_name:'create_workflow',tool_call_id:'tool-1',content:{workflow_id:'workflow-1',message:'Saved workflow'},quality}];await page.getByRole('textbox',{name:'Message input'}).fill('Show the recorded review result.');await page.getByRole('button',{name:'Send message',exact:true}).click();const open=page.getByRole('button',{name:'Quality Good, score 80 of 100. Show details.',exact:true});await open.focus();await page.keyboard.press('Enter');const details=page.getByRole('region',{name:'Tool quality details'});await details.waitFor();assert.ok(await details.evaluate(e=>e===document.activeElement));const bounds=await details.boundingBox();assert.ok(bounds.x>=0&&bounds.y>=0&&bounds.x+bounds.width<=width&&bounds.y+bounds.height<=page.viewportSize().height);await details.getByText(/85 vs 70 baseline/).waitFor();await shot('quality-details-'+width);await page.keyboard.press('Escape');await details.waitFor({state:'hidden'});assert.ok(await open.evaluate(e=>e===document.activeElement));await open.click();await page.getByRole('button',{name:'Close quality details',exact:true}).click();assert.ok(await open.evaluate(e=>e===document.activeElement))
 }
 assert.deepEqual(review.errors,[]);assert.deepEqual([...review.unmatched],[]);review.observations.push('Quality details remain within short/mobile viewports, allow scrolling, focus their readable region, close with Escape or named action and restore trigger. Measured test evidence, baseline comparison and pending settings are distinguished. Synthetic tool result only.')
}catch(error){await review.capture('quality-details-blocked',String(error));throw error}finally{await review.flush();await review.browser.close()}
