/**
 * Cost model behind the Docs → Cost Estimator section.
 *
 * The numbers here are *starting assumptions*, not measurements. Every LLM call
 * in the app is metered at a single chokepoint (MeteredModel → record_usage) and
 * written to the `llm_usage` collection with a `feature` label, so a deployment
 * with real traffic should calibrate these defaults against its own ledger
 * rather than trusting them. The operation ids below deliberately mirror the
 * metering feature names used in the backend.
 */

export interface Operation {
  /** Matches the `feature` label written to the llm_usage ledger. */
  id: string
  label: string
  /** What one unit of this operation is. */
  unit: string
  description: string
  /** Prompt tokens for one operation, including re-sent context. */
  inputTokens: number
  /** Completion tokens for one operation. */
  outputTokens: number
}

/**
 * Per-operation token draw. Rationale for each figure:
 *
 * - `extraction` runs the two-pass strategy by default (extraction_engine
 *   `mode: "two_pass"`), so the document body is sent through the model twice.
 *   ~30 pages of prose is ~15k tokens, hence ~30k input.
 * - `chat` is RAG-backed: k retrieved chunks (chunks default to 8000 characters,
 *   ~2k tokens each) plus the running conversation history.
 * - `workflow` chains extraction steps with dependency resolution; a 5-step
 *   workflow re-sends context per step.
 * - `classification` + `title_gen` fire once per uploaded document.
 * - `validation` covers the autotune / validation runs that judge output quality.
 *
 * Document *ingestion* itself is absent on purpose: embeddings are generated by
 * ChromaDB's local DefaultEmbeddingFunction, so chunking and indexing cost no
 * API tokens at all. Only the classification/title pass on upload is billable.
 */
export const OPERATIONS: Operation[] = [
  {
    id: 'classification',
    label: 'Document upload',
    unit: 'documents',
    description:
      'Classification + title generation on upload. Embedding and indexing are local (ChromaDB) and cost nothing.',
    inputTokens: 3_000,
    outputTokens: 300,
  },
  {
    id: 'extraction',
    label: 'Extraction run',
    unit: 'extractions',
    description:
      'One structured extraction over a ~30-page document using the default two-pass strategy.',
    inputTokens: 30_000,
    outputTokens: 2_000,
  },
  {
    id: 'chat',
    label: 'Chat message',
    unit: 'messages',
    description:
      'One RAG-backed question: retrieved chunks plus conversation history in, an answer with citations out.',
    inputTokens: 12_000,
    outputTokens: 700,
  },
  {
    id: 'workflow',
    label: 'Workflow run',
    unit: 'runs',
    description: 'A ~5-step workflow chaining extractions with dependency resolution.',
    inputTokens: 60_000,
    outputTokens: 4_000,
  },
  {
    id: 'validation',
    label: 'Validation / autotune run',
    unit: 'runs',
    description:
      'A judge-scored validation or "Validate & improve" tuning pass over a workflow, extraction, or KB.',
    inputTokens: 40_000,
    outputTokens: 3_000,
  },
]

export type OperationCounts = Record<string, number>

export interface WorkloadPreset {
  id: string
  label: string
  description: string
  counts: OperationCounts
}

/**
 * Monthly volume per *user*, by how heavily that person leans on the platform.
 * Sized for research administration: a proposal-heavy month for a working
 * sponsored-programs officer is the "Typical" column.
 */
export const WORKLOAD_PRESETS: WorkloadPreset[] = [
  {
    id: 'light',
    label: 'Light',
    description:
      'Occasional user — checks a handful of solicitations a month and asks the odd compliance question.',
    counts: { classification: 10, extraction: 15, chat: 40, workflow: 2, validation: 0 },
  },
  {
    id: 'typical',
    label: 'Typical',
    description:
      'Working research administrator — reviews solicitations and subawards steadily through the month.',
    counts: { classification: 40, extraction: 120, chat: 200, workflow: 15, validation: 2 },
  },
  {
    id: 'heavy',
    label: 'Heavy',
    description:
      'Power user or office lead — drives bulk intake, runs workflows across whole portfolios, tunes prompts.',
    counts: { classification: 120, extraction: 400, chat: 600, workflow: 60, validation: 8 },
  },
]

export interface ModelPrice {
  id: string
  label: string
  provider: string
  /** USD per 1M input tokens. */
  inputPerMTok: number
  /** USD per 1M output tokens. */
  outputPerMTok: number
  note?: string
}

/**
 * List prices in USD per million tokens, captured 2026-07-31.
 *
 * Anthropic figures are first-party API rates. OpenAI and Google figures are the
 * best public rates available at capture time and move more often than this file
 * does — the UI lets an admin override any rate, and should be used to do so
 * rather than treating these as current.
 */
export const MODEL_PRICES: ModelPrice[] = [
  {
    id: 'claude-opus-5',
    label: 'Claude Opus 5',
    provider: 'Anthropic',
    inputPerMTok: 5,
    outputPerMTok: 25,
  },
  {
    id: 'claude-sonnet-5',
    label: 'Claude Sonnet 5',
    provider: 'Anthropic',
    inputPerMTok: 3,
    outputPerMTok: 15,
    note: 'Introductory rate of $2 / $10 applies through 2026-08-31.',
  },
  {
    id: 'claude-haiku-4-5',
    label: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    inputPerMTok: 1,
    outputPerMTok: 5,
  },
  {
    id: 'gpt-5-6-sol',
    label: 'GPT-5.6 Sol',
    provider: 'OpenAI',
    inputPerMTok: 5,
    outputPerMTok: 30,
  },
  {
    id: 'gpt-5-6-terra',
    label: 'GPT-5.6 Terra',
    provider: 'OpenAI',
    inputPerMTok: 2,
    outputPerMTok: 12,
    note: 'OpenAI cut Terra and Luna rates on 2026-07-30; confirm against openai.com/api/pricing before budgeting.',
  },
  {
    id: 'gemini-3-1-pro',
    label: 'Gemini 3.1 Pro',
    provider: 'Google',
    inputPerMTok: 2,
    outputPerMTok: 12,
    note: 'Applies to prompts under 200K tokens; longer prompts move to $4 / $18.',
  },
  {
    id: 'gemini-3-6-flash',
    label: 'Gemini 3.6 Flash',
    provider: 'Google',
    inputPerMTok: 1.5,
    outputPerMTok: 7.5,
  },
]

export interface EstimateInput {
  counts: OperationCounts
  inputPerMTok: number
  outputPerMTok: number
  /** Users on the deployment. */
  users: number
  /**
   * Share of input tokens served from the provider's prompt cache, 0–1. Repeated
   * document and knowledge-base context is highly cacheable; cached reads bill at
   * roughly a tenth of the standard input rate.
   */
  cacheHitRate?: number
  operations?: Operation[]
}

export interface OperationEstimate {
  operation: Operation
  count: number
  inputTokens: number
  outputTokens: number
  cost: number
}

export interface Estimate {
  perOperation: OperationEstimate[]
  inputTokens: number
  outputTokens: number
  costPerUser: number
  costTotal: number
}

/** Cached input tokens bill at ~10% of the standard input rate. */
const CACHE_READ_MULTIPLIER = 0.1

const clamp01 = (n: number) => Math.min(1, Math.max(0, n))

/** Non-finite or negative inputs collapse to 0 so a half-typed field can't produce NaN. */
const safe = (n: number) => (Number.isFinite(n) && n > 0 ? n : 0)

export function estimate({
  counts,
  inputPerMTok,
  outputPerMTok,
  users,
  cacheHitRate = 0,
  operations = OPERATIONS,
}: EstimateInput): Estimate {
  const hitRate = clamp01(safe(cacheHitRate))
  const inRate = safe(inputPerMTok)
  const outRate = safe(outputPerMTok)
  // Blended input rate: the cached share bills at the discounted read rate.
  const effectiveInRate = inRate * (1 - hitRate) + inRate * CACHE_READ_MULTIPLIER * hitRate

  const perOperation = operations.map((operation) => {
    const count = Math.round(safe(counts[operation.id] ?? 0))
    const inputTokens = count * operation.inputTokens
    const outputTokens = count * operation.outputTokens
    return {
      operation,
      count,
      inputTokens,
      outputTokens,
      cost: (inputTokens / 1e6) * effectiveInRate + (outputTokens / 1e6) * outRate,
    }
  })

  const inputTokens = perOperation.reduce((sum, r) => sum + r.inputTokens, 0)
  const outputTokens = perOperation.reduce((sum, r) => sum + r.outputTokens, 0)
  const costPerUser = perOperation.reduce((sum, r) => sum + r.cost, 0)

  return {
    perOperation,
    inputTokens,
    outputTokens,
    costPerUser,
    costTotal: costPerUser * Math.max(0, Math.round(safe(users))),
  }
}

export function formatUsd(value: number): string {
  if (!Number.isFinite(value)) return '$0.00'
  if (value > 0 && value < 0.01) return '<$0.01'
  return value.toLocaleString('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: value >= 100 ? 0 : 2,
  })
}

export function formatTokens(value: number): string {
  if (!Number.isFinite(value) || value <= 0) return '0'
  if (value >= 1e9) return `${(value / 1e9).toFixed(1)}B`
  if (value >= 1e6) return `${(value / 1e6).toFixed(1)}M`
  if (value >= 1e3) return `${(value / 1e3).toFixed(0)}K`
  return String(Math.round(value))
}
