import { act, renderHook, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { useKBValidationRun } from './useKBValidationRun'
import { ApiError } from '../api/client'
import { getActiveKBValidationTask, getKBValidationTask, runKBValidationAsync } from '../api/knowledge'
vi.mock('../api/knowledge', () => ({ getActiveKBValidationTask: vi.fn(), getKBValidationTask: vi.fn(), runKBValidationAsync: vi.fn() }))
const start = vi.mocked(runKBValidationAsync), status = vi.mocked(getKBValidationTask)
const id = '00000000-0000-4000-8000-000000000001'
beforeEach(() => {
  vi.clearAllMocks()
  vi.spyOn(crypto, 'randomUUID').mockReturnValue(id)
  vi.mocked(getActiveKBValidationTask).mockResolvedValue({ task: null })
  start.mockResolvedValue({ task_id: id, status: 'queued' })
  status.mockResolvedValue({ task_id: id, status: 'queued', message: 'Waiting' })
})
afterEach(() => { vi.restoreAllMocks() })

describe('validation task lifecycle', () => {
  it('guards rapid starts and retains delayed/retrying state without a second POST', async () => {
    status.mockResolvedValue({ task_id: id, status: 'retrying', delayed: true })
    const { result, rerender } = renderHook(() => useKBValidationRun('kb', vi.fn()))
    await waitFor(() => expect(result.current.running).toBe(false))
    act(() => { result.current.start('judge'); result.current.start('judge+baseline') })
    await waitFor(() => expect(result.current.progress?.phase).toBe('retrying'))
    rerender()
    act(() => result.current.start('judge'))
    expect(start).toHaveBeenCalledTimes(1)
    expect(result.current.running).toBe(true)
    expect(result.current.progress?.delayed).toBe(true)
  })
  it('recovers a lost start response with the same request ID and options', async () => {
    start.mockRejectedValueOnce(new Error('lost response'))
    const { result } = renderHook(() => useKBValidationRun('kb', vi.fn()))
    await waitFor(() => expect(result.current.running).toBe(false))
    act(() => result.current.start('judge', ['q1']))
    await waitFor(() => expect(result.current.progress?.phase).toBe('connection'))
    act(() => result.current.retry())
    await waitFor(() => expect(result.current.progress?.phase).toBe('queued'))
    expect(start.mock.calls[0]).toEqual(start.mock.calls[1])
    expect(start.mock.calls[1][1]?.request_id).toBe(id)
  })
  it('recovers polling errors without resubmitting, and accepts only its exact task result', async () => {
    const done = vi.fn()
    status.mockRejectedValueOnce(new Error('offline'))
    const { result } = renderHook(() => useKBValidationRun('kb', done))
    await waitFor(() => expect(result.current.running).toBe(false))
    act(() => result.current.start('judge'))
    await waitFor(() => expect(result.current.progress?.phase).toBe('connection'))
    status.mockResolvedValueOnce({ task_id: 'someone-else', status: 'completed', run_uuid: 'wrong', result: {} as never })
    act(() => result.current.retry())
    await waitFor(() => expect(status).toHaveBeenCalledTimes(2))
    expect(done).not.toHaveBeenCalled()
    status.mockResolvedValueOnce({ task_id: id, status: 'completed', run_uuid: 'correct', result: { raw_score: 72 } as never })
    act(() => result.current.retry())
    await waitFor(() => expect(done).toHaveBeenCalledWith('correct', { raw_score: 72 }))
    expect(start).toHaveBeenCalledTimes(1)
    expect(result.current.running).toBe(false)
  })
  it('unlocks a confirmed worker failure or rejected input, and keeps unknown outcomes locked', async () => {
    status.mockResolvedValue({ task_id: id, status: 'unknown' })
    const { result } = renderHook(() => useKBValidationRun('kb', vi.fn()))
    await waitFor(() => expect(result.current.running).toBe(false))
    act(() => result.current.start('judge'))
    await waitFor(() => expect(result.current.progress?.phase).toBe('unknown'))
    expect(result.current.running).toBe(true)
    status.mockResolvedValue({ task_id: id, status: 'failed', message: 'Check failed' })
    act(() => result.current.retry())
    await waitFor(() => expect(result.current.running).toBe(false))
    start.mockRejectedValueOnce(new ApiError(400, 'Refresh stale questions'))
    await waitFor(() => expect(result.current.running).toBe(false))
    act(() => result.current.start('judge'))
    await waitFor(() => expect(result.current.progress?.message).toBe('Refresh stale questions'))
    expect(result.current.running).toBe(false)
  })
  it('ignores completion after the panel unmounts', async () => {
    let finish!: (value: Awaited<ReturnType<typeof getKBValidationTask>>) => void
    status.mockReturnValue(new Promise(resolve => { finish = resolve }))
    const done = vi.fn()
    const { result, unmount } = renderHook(() => useKBValidationRun('kb', done))
    await waitFor(() => expect(result.current.running).toBe(false))
    act(() => result.current.start('judge'))
    await waitFor(() => expect(status).toHaveBeenCalledTimes(1))
    unmount()
    await act(async () => finish({ task_id: id, status: 'completed', run_uuid: 'saved', result: {} as never }))
    expect(done).not.toHaveBeenCalled()
  })
})

describe('server-backed resumption', () => {
  it('restores a queued subset after remount without POSTing', async () => {
    vi.mocked(getActiveKBValidationTask).mockResolvedValue({ task: { task_id: id, status: 'running', options: { mode: 'judge', query_uuids: ['q1'] } } })
    status.mockResolvedValue({ task_id: id, status: 'running' })
    const first = renderHook(() => useKBValidationRun('kb', vi.fn()))
    await waitFor(() => expect(first.result.current.progress?.phase).toBe('running'))
    first.unmount()
    const second = renderHook(() => useKBValidationRun('kb', vi.fn()))
    await waitFor(() => expect(second.result.current.progress?.phase).toBe('running'))
    expect(second.result.current.activeOptions).toEqual({ mode: 'judge', query_uuids: ['q1'] })
    expect(start).not.toHaveBeenCalled()
  })
  it('restores completion that happened while the panel was closed', async () => {
    const done = vi.fn()
    vi.mocked(getActiveKBValidationTask).mockResolvedValue({ task: { task_id: id, status: 'completed', run_uuid: 'saved', result: { raw_score: 80 } as never, options: { mode: 'judge' } } })
    const { result } = renderHook(() => useKBValidationRun('kb', done))
    await waitFor(() => expect(done).toHaveBeenCalledWith('saved', { raw_score: 80 }))
    expect(result.current.running).toBe(false)
    expect(start).not.toHaveBeenCalled()
  })
  it('blocks starting while discovery fails and recovers without a new task', async () => {
    vi.mocked(getActiveKBValidationTask).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({ task: null })
    const { result } = renderHook(() => useKBValidationRun('kb', vi.fn()))
    await waitFor(() => expect(result.current.progress?.phase).toBe('connection'))
    act(() => result.current.start('judge'))
    expect(start).not.toHaveBeenCalled()
    act(() => result.current.retry())
    await waitFor(() => expect(result.current.running).toBe(false))
  })
  it('adopts the check started by another window during the discovery/start race', async () => {
    const other = '00000000-0000-4000-8000-000000000002'
    start.mockResolvedValue({ task_id: other, status: 'queued', resumed: true, options: { mode: 'judge', query_uuids: ['q2'] } })
    status.mockResolvedValue({ task_id: other, status: 'running' })
    const { result } = renderHook(() => useKBValidationRun('kb', vi.fn()))
    await waitFor(() => expect(result.current.running).toBe(false))
    act(() => result.current.start('judge+baseline'))
    await waitFor(() => expect(result.current.progress?.phase).toBe('running'))
    expect(status).toHaveBeenCalledWith('kb', other)
    expect(result.current.activeOptions?.query_uuids).toEqual(['q2'])
    expect(start).toHaveBeenCalledTimes(1)
  })
})
