"""An extraction can succeed and still not be the whole document.

Two failure modes were invisible. `parse_docling_response` kept
`partial_success` text with only a log line, so a 400-page scan whose OCR gave
up after thirty pages was stored as a complete document. And the only length
check, `MIN_PDF_TEXT_LENGTH = 100`, is a whole-document floor: 150 characters
is an ordinary result for one page and a total failure spread over 400.

Separately, `provider="raw"` returned `resp.text` verbatim with no
content-type check, so a wrapper answering HTTP 200 with an HTML error page had
that page stored as the document's text, chunked, embedded, and answered
questions from.
"""

from unittest.mock import MagicMock

import pytest

from app.services import document_service
from app.services.ocr_client import (
    OcrRequestError,
    _reject_non_text_body,
    is_retryable,
    parse_docling_response,
)
from app.utils.extraction_quality import (
    MIN_CHARS_PER_PAGE,
    chars_per_page,
    is_sparse_extraction,
)


class TestPartialDoclingConversion:
    def test_partial_success_is_reported_not_just_logged(self):
        report: dict = {}
        text = parse_docling_response(
            {
                "status": "partial_success",
                "errors": ["page 31: timeout", "page 32: timeout"],
                "document": {"md_content": "converted text"},
            },
            report,
        )
        assert text == "converted text"
        assert report["partial"] is True
        assert len(report["errors"]) == 2

    def test_errors_alone_count_as_partial(self):
        report: dict = {}
        parse_docling_response(
            {"status": "success", "errors": ["page 9 failed"],
             "document": {"md_content": "text"}},
            report,
        )
        assert report["partial"] is True

    def test_a_clean_conversion_reports_nothing(self):
        report: dict = {}
        assert parse_docling_response(
            {"status": "success", "document": {"md_content": "text"}}, report,
        ) == "text"
        assert report == {}

    def test_the_report_stays_optional(self):
        """Existing callers pass no report and must be unaffected."""
        assert parse_docling_response(
            {"status": "partial_success", "errors": ["x"],
             "document": {"md_content": "text"}},
        ) == "text"

    def test_a_failure_still_raises(self):
        with pytest.raises(OcrRequestError):
            parse_docling_response({"status": "failure", "errors": ["boom"]}, {})


class TestRawProviderBody:
    def _resp(self, text: str, content_type: str) -> MagicMock:
        resp = MagicMock()
        resp.text = text
        resp.status_code = 200
        resp.headers = {"Content-Type": content_type}
        return resp

    def test_an_html_error_page_is_not_document_text(self):
        with pytest.raises(OcrRequestError, match="not extracted text"):
            _reject_non_text_body(
                self._resp("<!DOCTYPE html><html><body>502 Bad Gateway</body></html>",
                           "text/html; charset=utf-8")
            )

    def test_markup_is_rejected_even_when_the_content_type_lies(self):
        with pytest.raises(OcrRequestError, match="markup document"):
            _reject_non_text_body(
                self._resp("<html><body>Gateway Timeout</body></html>", "text/plain")
            )

    def test_plain_text_passes(self):
        _reject_non_text_body(self._resp("Award Amount: $4,200,000", "text/plain; charset=utf-8"))

    def test_text_html_is_rejected_by_the_content_type_gate_itself(self):
        """The allowlist was a `startswith` tuple ending in "text/", which
        accepted text/html — the exact thing it exists to reject. The gate was
        a no-op and only the body sniff was working."""
        with pytest.raises(OcrRequestError, match="not extracted text"):
            _reject_non_text_body(self._resp("plain looking text", "text/html"))

    def test_an_error_page_behind_a_comment_is_still_markup(self):
        with pytest.raises(OcrRequestError, match="markup document"):
            _reject_non_text_body(self._resp(
                "<!-- generated by gateway -->\n<html><body>502</body></html>",
                "text/plain",
            ))

    def test_a_bom_does_not_hide_markup(self):
        with pytest.raises(OcrRequestError, match="markup document"):
            _reject_non_text_body(self._resp(
                "\ufeff<!DOCTYPE html><html></html>", "text/plain",
            ))

    def test_rejection_is_permanent_not_a_retry_storm(self):
        """A wrapper answering 200 with an error page is misconfigured, not
        overloaded. Classed retryable it burned all in-process attempts and
        then minutes of Celery backoff before the document was written off —
        instead of falling through to the PyMuPDF path one exception away."""
        from app.services.ocr_client import is_retryable

        try:
            _reject_non_text_body(self._resp("<html></html>", "text/html"))
        except OcrRequestError as e:
            assert is_retryable(e) is False
        else:
            raise AssertionError("expected OcrRequestError")

    def test_a_genuine_server_error_stays_retryable(self):
        assert is_retryable(OcrRequestError("boom", status_code=503)) is True

    def test_a_missing_content_type_is_not_grounds_for_rejection(self):
        """Plenty of small OCR wrappers send no Content-Type at all; the body
        check still applies, but an absent header alone must not fail a run."""
        _reject_non_text_body(self._resp("Award Amount: $4,200,000", ""))


class TestSparseExtraction:
    def test_a_400_page_scan_yielding_150_chars_is_sparse(self):
        """It clears MIN_PDF_TEXT_LENGTH = 100 and is still a total failure."""
        assert is_sparse_extraction("x" * 150, 400) is True

    def test_the_same_150_chars_on_one_page_is_not(self):
        assert is_sparse_extraction("x" * 150, 1) is False

    def test_whitespace_does_not_count_toward_density(self):
        padded = ("x" * 10 + " " * 500) * 3
        assert is_sparse_extraction(padded, 5) is True

    def test_an_unknown_page_count_is_never_sparse(self):
        assert is_sparse_extraction("x" * 10, None) is False
        assert is_sparse_extraction("x" * 10, 0) is False
        assert chars_per_page("xxx", 0) is None

    def test_the_floor_is_the_boundary(self):
        assert is_sparse_extraction("x" * MIN_CHARS_PER_PAGE, 1) is False
        assert is_sparse_extraction("x" * (MIN_CHARS_PER_PAGE - 1), 1) is True


class TestSurfacing:
    def _doc(self, warnings, title="Big Package.pdf"):
        doc = MagicMock()
        doc.ingestion_warnings = warnings
        doc.title = title
        doc.uuid = "d-1"
        doc.raw_text = "some text"
        return doc

    def test_warnings_become_readable_text(self):
        doc = self._doc(["partial_ocr", "sparse_text"])
        text = document_service.ingestion_warning_text(doc)
        assert "only part of this document" in text
        assert "far less text" in text
        assert document_service.is_partially_ingested(doc) is True

    def test_the_extraction_paths_low_quality_code_has_a_label(self):
        """`search_set_service` emits this code; without an entry in the label
        map `ingestion_warnings()` filtered it straight back out, so the
        extraction run reported a warning that rendered as nothing."""
        doc = self._doc(["low_quality_text"])
        assert document_service.ingestion_warnings(doc) == ["low_quality_text"]
        assert "unreadable" in document_service.ingestion_warning_text(doc)

    def test_unknown_codes_are_ignored(self):
        """A code we no longer emit must not render as a blank warning."""
        doc = self._doc(["some_retired_code"])
        assert document_service.ingestion_warnings(doc) == []
        assert document_service.is_partially_ingested(doc) is False

    def test_a_clean_document_carries_no_warning(self):
        assert document_service.ingestion_warning_text(self._doc([])) == ""

    def test_a_legacy_document_without_the_field_is_clean(self):
        doc = MagicMock(spec=["title", "uuid", "raw_text"])
        doc.title, doc.uuid, doc.raw_text = "Old.pdf", "d-2", "text"
        assert document_service.ingestion_warnings(doc) == []

    def test_chat_names_the_partial_documents(self):
        from app.services.chat_service import partially_ingested_titles

        titles = partially_ingested_titles([
            self._doc(["partial_ocr"], title="Proposal.pdf"),
            self._doc([], title="Clean.pdf"),
        ])
        assert len(titles) == 1
        assert titles[0].startswith("Proposal.pdf (")

    def test_chat_skips_documents_with_no_text(self):
        doc = self._doc(["partial_ocr"])
        doc.raw_text = ""
        from app.services.chat_service import partially_ingested_titles

        assert partially_ingested_titles([doc]) == []


class TestEveryRunPathDiscloses:
    """The failure mode this guards is not a wrong value but a fix applied to
    one path and quietly not to its siblings: the in-app run disclosed a
    half-read document while `/run-integrated` and the management API, given
    the identical input, said nothing. Asserted structurally because the point
    is coverage of *every* call site, which no single request-level test can
    show."""

    def _call_sites(self):
        import ast
        import pathlib

        root = pathlib.Path(__file__).resolve().parents[1] / "app" / "routers"
        sites = []
        for path in (root / "extractions.py", root / "mgmt.py"):
            tree = ast.parse(path.read_text())
            for node in ast.walk(tree):
                if not isinstance(node, ast.Call):
                    continue
                fn = node.func
                if isinstance(fn, ast.Attribute) and fn.attr == "run_extraction_sync":
                    sites.append((path.name, node.lineno,
                                  {k.arg for k in node.keywords}))
        return sites

    def test_there_are_call_sites_to_check(self):
        # Guards the guard: a renamed method would otherwise pass vacuously.
        assert len(self._call_sites()) >= 3

    def test_no_run_path_swallows_a_degraded_document(self):
        missing = [
            f"{name}:{lineno}"
            for name, lineno, kwargs in self._call_sites()
            if "document_warnings" not in kwargs
        ]
        assert not missing, (
            "these run paths extract from a possibly half-read document and "
            f"report nothing about it: {missing}"
        )


class TestNoExtractableTextFlagging:
    """One writer for the per-document no_extractable_text disclosure, so the
    entry shape and dedupe rule cannot drift between the nothing-readable
    pre-flight, the combined-context merge, and the engine-skipped loop."""

    def test_creates_and_dedupes_entries(self):
        from app.services.search_set_service import _flag_no_extractable_text

        warnings: list[dict] = []
        _flag_no_extractable_text(warnings, "d1", "Award letter")
        _flag_no_extractable_text(warnings, "d1", "Award letter")
        assert len(warnings) == 1
        entry = warnings[0]
        assert entry["document_uuid"] == "d1"
        assert entry["title"] == "Award letter"
        assert entry["codes"] == ["no_extractable_text"]
        # The human sentence rides along so the frontend never needs its own
        # copy of the code→text map (#803).
        assert "could not be read" in entry["text"]

    def test_merges_into_an_existing_documents_entry(self):
        from app.services.search_set_service import _flag_no_extractable_text

        warnings = [{"document_uuid": "d1", "title": "T", "codes": ["partial_ocr"]}]
        _flag_no_extractable_text(warnings, "d1", "T")
        assert warnings[0]["codes"] == ["partial_ocr", "no_extractable_text"]

    def test_none_out_list_is_a_no_op(self):
        from app.services.search_set_service import _flag_no_extractable_text

        _flag_no_extractable_text(None, "d1", "T")  # must not raise

    def test_code_has_a_label_registered_for_the_renderer(self):
        """The registry's own comment records how low_quality_text once
        rendered as nothing for lack of an entry here."""
        from app.services.document_service import INGESTION_WARNING_LABELS

        assert "no_extractable_text" in INGESTION_WARNING_LABELS


class TestWarningTextReachesEveryDocumentSurface:
    """The caveat icon keys on `ingestion_warning_text`. Serving it from only
    one endpoint left the file browser — the screen #803 is actually about —
    rendering a clean row, and the component tests couldn't catch it because
    they hand-build the prop."""

    def test_every_document_payload_builder_emits_the_text(self):
        import inspect

        from app.services import document_service

        # The two builders that feed a document row: the folder listing (the
        # file browser) and the post-upload poll.
        for fn in (document_service.list_contents, document_service.poll_status):
            source = inspect.getsource(fn)
            assert '"ingestion_warnings"' in source, f"{fn.__name__} lost the codes"
            assert '"ingestion_warning_text"' in source, (
                f"{fn.__name__} serves warning codes without the words the UI "
                "renders — the caveat will not appear"
            )

    def test_completeness_codes_only_reach_the_not_read_in_full_headline(self):
        """hidden_text_unchecked is the INVERSE risk (extra unvetted content,
        not missing content); announcing it as 'not read in full' asserts the
        opposite of what happened."""
        from app.services.document_service import COMPLETENESS_WARNING_CODES

        assert "hidden_text_unchecked" not in COMPLETENESS_WARNING_CODES
        assert "partial_ocr" in COMPLETENESS_WARNING_CODES

    def test_merging_a_severer_code_recomposes_the_text(self):
        from app.services.search_set_service import _flag_no_extractable_text

        warnings = [{
            "document_uuid": "d1", "title": "T",
            "codes": ["sparse_text"],
            "text": "far less text than its page count suggests",
        }]
        _flag_no_extractable_text(warnings, "d1", "T")
        # The strip renders `text`; a stale one reported the milder caveat.
        assert "could not be read" in warnings[0]["text"]
        assert warnings[0]["codes"] == ["sparse_text", "no_extractable_text"]
