name: "vandalizer-demo-${VANDALIZER_INSTANCE_NUMBER:-0}"
services:
  vandalizer-preload:
    image: ghcr.io/ui-iids/vandalizer-demo-preload:main
    networks:
      - vandalizer
    volumes:
      - "vandalizer:/app/app/static/uploads"
  redis:
    image: redis/redis-stack:latest
    networks:
      - vandalizer
    restart: always
  mongo:
    image: ghcr.io/ui-iids/vandalizer-demo-mongo:main
    networks:
      - vandalizer
    restart: always
  celery:
    image: ghcr.io/ui-iids/vandalizer:main
    depends_on:
      - redis
      - mongo
      - vandalizer-preload
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongo:27017
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - vandalizer
    volumes:
      - "vandalizer:/app/app/static/uploads"
    entrypoint: sh run_celery.sh
    restart: always
  web:
    image: ghcr.io/ui-iids/vandalizer:main
    ports:
      - "${VANDALIZER_PORT_NUMBER:-8000}:8000"
    depends_on:
      - redis
      - mongo
      - celery
      - vandalizer-preload
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongo:27017
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - vandalizer
    volumes:
      - "vandalizer:/app/app/static/uploads"
    restart: always

networks:
  vandalizer:
    name: "vandalizer-${VANDALIZER_INSTANCE_NUMBER:-0}"
    external: false
    ipam:
      driver: default
      config:
        - subnet: "10.20.${VANDALIZER_INSTANCE_NUMBER:-0}.0/24"
volumes:
  vandalizer:
    name: "vandalizer-${VANDALIZER_INSTANCE_NUMBER:-0}"
